// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO guilt_entries (
    session_id,
    entry_text,
    guilt_level
) VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    session_id,
    entry_text,
    guilt_level,
    roast_text,
    created_at,
    updated_at
`

type CreateEntryParams struct {
	SessionID  uuid.UUID
	EntryText  string
	GuiltLevel sql.NullInt32
}

type CreateEntryRow struct {
	ID         uuid.UUID
	SessionID  uuid.UUID
	EntryText  string
	GuiltLevel sql.NullInt32
	RoastText  sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (CreateEntryRow, error) {
	row := q.db.QueryRowContext(ctx, createEntry, arg.SessionID, arg.EntryText, arg.GuiltLevel)
	var i CreateEntryRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EntryText,
		&i.GuiltLevel,
		&i.RoastText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntriesBySession = `-- name: ListEntriesBySession :many
SELECT
    id,
    session_id,
    entry_text,
    guilt_level,
    roast_text,
    created_at,
    updated_at
FROM guilt_entries
WHERE session_id = $1
ORDER BY created_at ASC
`

type ListEntriesBySessionRow struct {
	ID         uuid.UUID
	SessionID  uuid.UUID
	EntryText  string
	GuiltLevel sql.NullInt32
	RoastText  sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) ListEntriesBySession(ctx context.Context, sessionID uuid.UUID) ([]ListEntriesBySessionRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesBySessionRow
	for rows.Next() {
		var i ListEntriesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EntryText,
			&i.GuiltLevel,
			&i.RoastText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoast = `-- name: UpdateRoast :exec
UPDATE guilt_entries SET roast_text = $2 WHERE id = $1
`

type UpdateRoastParams struct {
	ID        uuid.UUID
	RoastText sql.NullString
}

func (q *Queries) UpdateRoast(ctx context.Context, arg UpdateRoastParams) error {
	_, err := q.db.ExecContext(ctx, updateRoast, arg.ID, arg.RoastText)
	return err
}
