// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type GuiltEntry struct {
	ID         uuid.UUID
	SessionID  uuid.UUID
	EntryText  string
	GuiltLevel sql.NullInt32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type GuiltScore struct {
	ID             uuid.UUID
	SessionID      uuid.UUID
	AggregateScore int32
	Meta           pqtype.NullRawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GuiltSession struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	StartTime time.Time
	EndTime   sql.NullTime
	Notes     sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserPreference struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	Theme                sql.NullString
	NotificationsEnabled bool
	Metadata             pqtype.NullRawMessage
	CreatedAt            time.Time
	UpdatedAt            time.Time
}
