// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createScore = `-- name: CreateScore :one
INSERT INTO guilt_scores (
    session_id,
    aggregate_score,
    meta
) VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    session_id,
    aggregate_score,
    meta,
    created_at,
    updated_at
`

type CreateScoreParams struct {
	SessionID      uuid.UUID
	AggregateScore int32
	Meta           pqtype.NullRawMessage
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (GuiltScore, error) {
	row := q.db.QueryRowContext(ctx, createScore, arg.SessionID, arg.AggregateScore, arg.Meta)
	var i GuiltScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AggregateScore,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScoreBySession = `-- name: GetScoreBySession :one
SELECT
    id,
    session_id,
    aggregate_score,
    meta,
    created_at,
    updated_at
FROM guilt_scores
WHERE session_id = $1
`

func (q *Queries) GetScoreBySession(ctx context.Context, sessionID uuid.UUID) (GuiltScore, error) {
	row := q.db.QueryRowContext(ctx, getScoreBySession, sessionID)
	var i GuiltScore
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AggregateScore,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
