// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createScore = `-- name: CreateScore :one
INSERT INTO guilt_scores (
    session_id,
    entry_id,
    aggregate_score,
    meta
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    session_id,
    entry_id,
    aggregate_score,
    meta,
    created_at,
    updated_at
`

type CreateScoreParams struct {
	SessionID      uuid.UUID
	EntryID        uuid.NullUUID
	AggregateScore int32
	Meta           pqtype.NullRawMessage
}

type CreateScoreRow struct {
	ID             uuid.UUID
	SessionID      uuid.UUID
	EntryID        uuid.NullUUID
	AggregateScore int32
	Meta           pqtype.NullRawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) (CreateScoreRow, error) {
	row := q.db.QueryRowContext(ctx, createScore,
		arg.SessionID,
		arg.EntryID,
		arg.AggregateScore,
		arg.Meta,
	)
	var i CreateScoreRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EntryID,
		&i.AggregateScore,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScoreByEntry = `-- name: GetScoreByEntry :one
SELECT
    id,
    session_id,
    entry_id,
    aggregate_score,
    meta,
    created_at,
    updated_at
FROM guilt_scores
WHERE entry_id = $1
`

type GetScoreByEntryRow struct {
	ID             uuid.UUID
	SessionID      uuid.UUID
	EntryID        uuid.NullUUID
	AggregateScore int32
	Meta           pqtype.NullRawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetScoreByEntry(ctx context.Context, entryID uuid.NullUUID) (GetScoreByEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getScoreByEntry, entryID)
	var i GetScoreByEntryRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EntryID,
		&i.AggregateScore,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScoreBySession = `-- name: GetScoreBySession :one
SELECT
    id,
    session_id,
    entry_id,
    aggregate_score,
    meta,
    created_at,
    updated_at
FROM guilt_scores
WHERE session_id = $1
`

type GetScoreBySessionRow struct {
	ID             uuid.UUID
	SessionID      uuid.UUID
	EntryID        uuid.NullUUID
	AggregateScore int32
	Meta           pqtype.NullRawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetScoreBySession(ctx context.Context, sessionID uuid.UUID) (GetScoreBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getScoreBySession, sessionID)
	var i GetScoreBySessionRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EntryID,
		&i.AggregateScore,
		&i.Meta,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
