// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO guilt_sessions (
    user_id,
    notes
) VALUES (
    $1,
    $2
)
RETURNING
    id,
    user_id,
    start_time,
    end_time,
    notes,
    created_at,
    updated_at
`

type CreateSessionParams struct {
	UserID uuid.UUID
	Notes  sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (GuiltSession, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.Notes)
	var i GuiltSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const endSession = `-- name: EndSession :one
UPDATE guilt_sessions
SET
    end_time = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    user_id,
    start_time,
    end_time,
    notes,
    created_at,
    updated_at
`

func (q *Queries) EndSession(ctx context.Context, id uuid.UUID) (GuiltSession, error) {
	row := q.db.QueryRowContext(ctx, endSession, id)
	var i GuiltSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
    id,
    user_id,
    start_time,
    end_time,
    notes,
    created_at,
    updated_at
FROM guilt_sessions
WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (GuiltSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i GuiltSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT
    id,
    user_id,
    start_time,
    end_time,
    notes,
    created_at,
    updated_at
FROM guilt_sessions
WHERE user_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListSessionsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]GuiltSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuiltSession
	for rows.Next() {
		var i GuiltSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
