// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getPreferencesByUserID = `-- name: GetPreferencesByUserID :one
SELECT
    id,
    user_id,
    theme,
    notifications_enabled,
    metadata,
    created_at,
    updated_at
FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetPreferencesByUserID(ctx context.Context, userID uuid.UUID) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getPreferencesByUserID, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.NotificationsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (
    user_id,
    theme,
    notifications_enabled,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (user_id) DO UPDATE SET
    theme = EXCLUDED.theme,
    notifications_enabled = EXCLUDED.notifications_enabled,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING
    id,
    user_id,
    theme,
    notifications_enabled,
    metadata,
    created_at,
    updated_at
`

type UpsertUserPreferencesParams struct {
	UserID               uuid.UUID
	Theme                sql.NullString
	NotificationsEnabled bool
	Metadata             pqtype.NullRawMessage
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.NotificationsEnabled,
		arg.Metadata,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.NotificationsEnabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
